apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo-d9b6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo-d9b6"
  template:
    metadata:
      labels:
        app: "aksdemo-d9b6"
    spec:
      containers:
        - name: "aksdemo-d9b6"
          image: "slgacrdemo.azurecr.io/aksdemo"
          ports:
          - containerPort: 80