on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: slgacrdemo.azurecr.io
        username: ${{ secrets.acr_slgacrdemo_username }}
        password: ${{ secrets.acr_slgacrdemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t slgacrdemo.azurecr.io/aksdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push slgacrdemo.azurecr.io/aksdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksdemo9aba | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksdemo9aba`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksdemo9aba
        container-registry-url: slgacrdemo.azurecr.io
        container-registry-username: ${{ secrets.acr_slgacrdemo_username }}
        container-registry-password: ${{ secrets.acr_slgacrdemo_password }}
        secret-name: aksdemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksdemo9aba
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          slgacrdemo.azurecr.io/aksdemo:${{ github.sha }}
        imagepullsecrets: |
          aksdemodockerauth
